env:
  TERM: xterm-256color
window:
  decorations: none
  dynamic_title: true
  startup_mode: Maximized
  opacity: 0.95
  padding:
    x: 10
    y: 15

font:
  # Normal (roman) font face
  normal:
    family: Hack Nerd Font Mono
    style: Regular

  # Bold font face
  bold:
    family: Hack Nerd Font Mono
    style: Bold

  # Italic font face
  italic:
    family: Hack Nerd Font Mono
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic

  # Point size
  size: 13.5

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true
schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night # Default colors
    primary:
      background: '#1a1b26'
      foreground: '#a9b1d6'

    # Normal colors
    normal:
      black: '#32344a'
      red: '#f7768e'
      green: '#9ece6a'
      yellow: '#e0af68'
      blue: '#7aa2f7'
      magenta: '#ad8ee6'
      cyan: '#449dab'
      white: '#787c99'

    # Bright colors
    bright:
      black: '#444b6a'
      red: '#ff7a93'
      green: '#b9f27c'
      yellow: '#ff9e64'
      blue: '#7da6ff'
      magenta: '#bb9af7'
      cyan: '#0db9d7'
      white: '#acb0d0'

  tokyo-night-storm: &tokyo-night-storm # Default colors
    primary:
      background: '#24283b'
      foreground: '#a9b1d6'

    # Normal colors
    normal:
      black: '#32344a'
      red: '#f7768e'
      green: '#9ece6a'
      yellow: '#e0af68'
      blue: '#7aa2f7'
      magenta: '#ad8ee6'
      cyan: '#449dab'
      white: '#9699a8'

    # Bright colors
    bright:
      black: '#444b6a'
      red: '#ff7a93'
      green: '#b9f27c'
      yellow: '#ff9e64'
      blue: '#7da6ff'
      magenta: '#bb9af7'
      cyan: '#0db9d7'
      white: '#acb0d0'

  iceberg:
    # Default colors
    primary:
      background: '#161821'
      foreground: '#d2d4de'

      black: '#161821'
      red: '#e27878'
      green: '#b4be82'
      yellow: '#e2a478'
      blue: '#84a0c6'
      magenta: '#a093c7'
      cyan: '#89b8c2'
      white: '#c6c8d1'

    # Bright colors
    bright:
      black: '#6b7089'
      red: '#e98989'
      green: '#c0ca8e'
      yellow: '#e9b189'
      blue: '#91acd1'
      magenta: '#ada0d3'
      cyan: '#95c4ce'
      white: '#d2d4de'

  catppuccin-frappe: &catppuccin-frappe # Default colors
    primary:
      background: '#303446' # base
      foreground: '#C6D0F5' # text
      # Bright and dim foreground colors
      dim_foreground: '#C6D0F5' # text
      bright_foreground: '#C6D0F5' # text

    # Cursor colors
    cursor:
      text: '#303446' # base
      cursor: '#F2D5CF' # rosewater
    vi_mode_cursor:
      text: '#303446' # base
      cursor: '#BABBF1' # lavender

    # Search colors
    search:
      matches:
        foreground: '#303446' # base
        background: '#A5ADCE' # subtext0
      focused_match:
        foreground: '#303446' # base
        background: '#A6D189' # green
      footer_bar:
        foreground: '#303446' # base
        background: '#A5ADCE' # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: '#303446' # base
        background: '#E5C890' # yellow
      end:
        foreground: '#303446' # base
        background: '#A5ADCE' # subtext0

    # Selection colors
    selection:
      text: '#303446' # base
      background: '#F2D5CF' # rosewater

    # Normal colors
    normal:
      black: '#51576D' # surface1
      red: '#E78284' # red
      green: '#A6D189' # green
      yellow: '#E5C890' # yellow
      blue: '#8CAAEE' # blue
      magenta: '#F4B8E4' # pink
      cyan: '#81C8BE' # teal
      white: '#B5BFE2' # subtext1

    # Bright colors
    bright:
      black: '#626880' # surface2
      red: '#E78284' # red
      green: '#A6D189' # green
      yellow: '#E5C890' # yellow
      blue: '#8CAAEE' # blue
      magenta: '#F4B8E4' # pink
      cyan: '#81C8BE' # teal
      white: '#A5ADCE' # subtext0

    # Dim colors
    dim:
      black: '#51576D' # surface1
      red: '#E78284' # red
      green: '#A6D189' # green
      yellow: '#E5C890' # yellow
      blue: '#8CAAEE' # blue
      magenta: '#F4B8E4' # pink
      cyan: '#81C8BE' # teal
      white: '#B5BFE2' # subtext1

    indexed_colors:
      - { index: 16, color: '#EF9F76' }
      - { index: 17, color: '#F2D5CF' }

  catppuccin-mocha: &catppuccin-mocha
    primary:
      background: '#1E1E2E' # base
      foreground: '#CDD6F4' # text
      # Bright and dim foreground colors
      dim_foreground: '#CDD6F4' # text
      bright_foreground: '#CDD6F4' # text

    # Cursor colors
    cursor:
      text: '#1E1E2E' # base
      cursor: '#F5E0DC' # rosewater
    vi_mode_cursor:
      text: '#1E1E2E' # base
      cursor: '#B4BEFE' # lavender

    # Search colors
    search:
      matches:
        foreground: '#1E1E2E' # base
        background: '#A6ADC8' # subtext0
      focused_match:
        foreground: '#1E1E2E' # base
        background: '#A6E3A1' # green
      footer_bar:
        foreground: '#1E1E2E' # base
        background: '#A6ADC8' # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: '#1E1E2E' # base
        background: '#F9E2AF' # yellow
      end:
        foreground: '#1E1E2E' # base
        background: '#A6ADC8' # subtext0

    # Selection colors
    selection:
      text: '#1E1E2E' # base
      background: '#F5E0DC' # rosewater

    # Normal colors
    normal:
      black: '#45475A' # surface1
      red: '#F38BA8' # red
      green: '#A6E3A1' # green
      yellow: '#F9E2AF' # yellow
      blue: '#89B4FA' # blue
      magenta: '#F5C2E7' # pink
      cyan: '#94E2D5' # teal
      white: '#BAC2DE' # subtext1

    # Bright colors
    bright:
      black: '#585B70' # surface2
      red: '#F38BA8' # red
      green: '#A6E3A1' # green
      yellow: '#F9E2AF' # yellow
      blue: '#89B4FA' # blue
      magenta: '#F5C2E7' # pink
      cyan: '#94E2D5' # teal
      white: '#A6ADC8' # subtext0

    # Dim colors
    dim:
      black: '#45475A' # surface1
      red: '#F38BA8' # red
      green: '#A6E3A1' # green
      yellow: '#F9E2AF' # yellow
      blue: '#89B4FA' # blue
      magenta: '#F5C2E7' # pink
      cyan: '#94E2D5' # teal
      white: '#BAC2DE' # subtext1

    indexed_colors:
      - { index: 16, color: '#FAB387' }
      - { index: 17, color: '#F5E0DC' }

colors: *catppuccin-mocha
