env:
  TERM: xterm-256color
window:
  decorations: none
  dynamic_title: true
  startup_mode: Maximized
  opacity: 0.95
  padding:
    x: 10
    y: 15

font:
  # Normal (roman) font face
  normal:
    family: Hack Nerd Font Mono
    style: Regular

  # Bold font face
  bold:
    family: Hack Nerd Font Mono
    style: Bold

  # Italic font face
  italic:
    family: Hack Nerd Font Mono
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic

  # Point size
  size: 13.5

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true
schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '#1a1b26'
      foreground: '#a9b1d6'

    # Normal colors
    normal:
      black:   '#32344a'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#ad8ee6'
      cyan:    '#449dab'
      white:   '#787c99'

    # Bright colors
    bright:
      black:   '#444b6a'
      red:     '#ff7a93'
      green:   '#b9f27c'
      yellow:  '#ff9e64'
      blue:    '#7da6ff'
      magenta: '#bb9af7'
      cyan:    '#0db9d7'
      white:   '#acb0d0'

  tokyo-night-storm: &tokyo-night-storm
    # Default colors
    primary:
      background: '#24283b'
      foreground: '#a9b1d6'

    # Normal colors
    normal:
      black:   '#32344a'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#ad8ee6'
      cyan:    '#449dab'
      white:   '#9699a8'

    # Bright colors
    bright:
      black:   '#444b6a'
      red:     '#ff7a93'
      green:   '#b9f27c'
      yellow:  '#ff9e64'
      blue:    '#7da6ff'
      magenta: '#bb9af7'
      cyan:    '#0db9d7'
      white:   '#acb0d0'

  iceberg:
    # Default colors
    primary:
      background: '#161821'
      foreground: '#d2d4de'

      # Bright and dim foreground colors
      #
      # The dimmed foreground color is calculated automatically if it is not present.
      # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
      # is `false`, the normal foreground color will be used.
      #dim_foreground: '#9a9a9a'
      #bright_foreground: '#ffffff'

    # Cursor colors
    #
    # Colors which should be used to draw the terminal cursor. If these are unset,
    # the cursor color will be the inverse of the cell color.
    #cursor:
    #  text: '#000000'
    #  cursor: '#ffffff'

    # Selection colors
    #
    # Colors which should be used to draw the selection area. If selection
    # background is unset, selection color will be the inverse of the cell colors.
    # If only text is unset the cell text color will remain the same.
    #selection:
    #  text: '#eaeaea'
    #  background: '#404040'

    # Normal colors
    normal:
      black:   '#161821'
      red:     '#e27878'
      green:   '#b4be82'
      yellow:  '#e2a478'
      blue:    '#84a0c6'
      magenta: '#a093c7'
      cyan:    '#89b8c2'
      white:   '#c6c8d1'

    # Bright colors
    bright:
      black:   '#6b7089'
      red:     '#e98989'
      green:   '#c0ca8e'
      yellow:  '#e9b189'
      blue:    '#91acd1'
      magenta: '#ada0d3'
      cyan:    '#95c4ce'
      white:   '#d2d4de'

colors: *tokyo-night
