#!/bin/sh

# bspc config remove_disabled_monitors true
# bspc config remove_unplugged_monitors true

# Terminate already running bar instances
# killall -q polybar

# Wait until the processes have been shut down
# while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done


# ~/.config/bspwm/panel
