#! /bin/sh

bspc rule -r "*"

sxhkd &
$HOME/.config/bspwm/panel &

bspc config border_width        1
bspc config window_gap          5

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor HDMI1 -d web term misc
bspc monitor eDP1 -d I II III

bspc rule -a Chromium state=floating
bspc rule -a Google-chrome state=floating

bspc subscribe all | while read line; do polybar-msg hook title_bar 1; done &
