#! /bin/sh

sxhkd &
$HOME/.config/bspwm/panel &

bspc config border_width        1
bspc config window_gap          5

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor HDMI-1 -d I II III IV V
bspc monitor eDP-1 -d VI VII VIII IX X

bspc rule -a * floating=on
