#! /bin/sh

sxhkd &
$HOME/.config/bspwm/panel &

bspc config border_width        1
bspc config window_gap          5

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor eDP-1 -n L
bspc monitor HDMI-1 -n R
bspc monitor R -s L
bspc monitor L -d ""
bspc monitor R -d ""

bspc rule -a * floating=on
