#!/bin/sh

if [ -z "$(pgrep -x polybar)" ]; then
    for m in $(polybar --list-monitors | cut -d":" -f1); do
        MONITOR=$m polybar -r left &
        MONITOR=$m polybar -r center &
        MONITOR=$m polybar -r right &
        sleep 1
    done
else
    polybar-msg cmd restart
fi

echo "Bars launched..."
