#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
        MONITOR=$m polybar -r left &
        MONITOR=$m polybar -r center &
        MONITOR=$m polybar -r right &
    done
else
    polybar -r left &
    polybar -r center &
    polybar -r right &
fi

echo "Bars launched..."
