alias = {
    'brave-browser': ['', 'brave'],
    'google-chrome': ['', 'chrome'],
    'kitty': ['', 'kitty'],
    'neovim': ['', 'vim'],
    'code': ['﬏', 'vscode'],
    'polkit-gnome-authentication-agent-1': ['', 'password'],
    'nitrogen': ['', 'nitrogen'],
    'thunar': ['', 'thunar'],
    'timeshift-gtk': ['', 'timeshift'],
    'font-manager': ['ﯔ', 'font manager'],
    'steam': ['', 'steam'],
    'mail': ['', 'email'],
    'thunderbird': ['', 'email'],
    'lxappearance': ['', 'lxappearance'],
    'gimp-2.10': ['', 'gimp'],
    'gpartedbin': ['', 'gparted'],
    }
